/* =========================================================================
   SUPABASE-BACKED SERVICE LAYER (Stage 2)
   -------------------------------------------------------------------------
   Drop-in reimplementation of the localStorage service layer against Supabase
   (Postgres). Every method here keeps the EXACT same name, parameters, and
   return shape (camelCase app objects via ../mappers.js) as the old
   src/services/index.js, so the React UI needs no changes.

   Scope of this file: companyService, clientService, contractService,
   paymentService. Auth/users (userService, getSession) are Stage 3 and are
   intentionally NOT reimplemented here.

   Conventions:
   - Every Supabase call returns { data, error }; on error we throw
     new Error(error.message).
   - Row primary keys / created_at are generated by the DB — we never send them
     on insert. Client-generated ids inside JSON blobs (e.g. reminders) use
     crypto.randomUUID().
   ========================================================================= */

import { supabase } from '../lib/supabase.js';
import {
  companyFromRow,
  companyToRow,
  clientFromRow,
  clientToRow,
  contractFromRow,
  contractToRow,
  paymentFromRow,
  paymentToRow,
} from './mappers.js';

// Small helper: throw on Supabase error, else return data.
function unwrap({ data, error }) {
  if (error) throw new Error(error.message);
  return data;
}

/* ============================== COMPANY ============================== */
export const companyService = {
  get: async () => {
    const rows = unwrap(
      await supabase.from('company').select('*').limit(1)
    );
    if (!rows || rows.length === 0) return null;
    return companyFromRow(rows[0]);
  },

  update: async (patch) => {
    // Find the existing (single logical) company row, if any.
    const existing = unwrap(
      await supabase.from('company').select('id').limit(1)
    );
    const rowPatch = companyToRow(patch);
    if (existing && existing.length > 0) {
      const updated = unwrap(
        await supabase
          .from('company')
          .update(rowPatch)
          .eq('id', existing[0].id)
          .select()
          .single()
      );
      return companyFromRow(updated);
    }
    const inserted = unwrap(
      await supabase.from('company').insert(rowPatch).select().single()
    );
    return companyFromRow(inserted);
  },

  clearClientsAndContracts: async () => {
    // Respect FK order: contracts reference clients (on delete restrict), so
    // delete contracts first, then clients. Deleting contracts cascades to
    // payments (on delete cascade).
    unwrap(
      await supabase
        .from('contracts')
        .delete()
        .not('id', 'is', null)
    );
    unwrap(
      await supabase
        .from('clients')
        .delete()
        .not('id', 'is', null)
    );
  },
};

/* ============================== CLIENTS ============================== */
export const clientService = {
  getAll: async () => {
    const rows = unwrap(
      await supabase.from('clients').select('*').order('company_name', { ascending: true })
    );
    return (rows || []).map(clientFromRow);
  },

  getById: async (id) => {
    const rows = unwrap(
      await supabase.from('clients').select('*').eq('id', id).limit(1)
    );
    if (!rows || rows.length === 0) return null;
    return clientFromRow(rows[0]);
  },

  create: async (data) => {
    // DB generates id + created_at — do not send them.
    const inserted = unwrap(
      await supabase.from('clients').insert(clientToRow(data)).select().single()
    );
    return clientFromRow(inserted);
  },

  update: async (id, patch) => {
    const updated = unwrap(
      await supabase
        .from('clients')
        .update(clientToRow(patch))
        .eq('id', id)
        .select()
        .single()
    );
    return clientFromRow(updated);
  },
};

/* ============================== CONTRACTS ============================== */
export const contractService = {
  getAll: async () => {
    // Fetch all contracts, then all payments, then group payments by
    // contract_id in JS (two queries total — efficient for this volume).
    const contractRows = unwrap(
      await supabase.from('contracts').select('*').order('created_at', { ascending: true })
    );
    if (!contractRows || contractRows.length === 0) return [];

    const paymentRows = unwrap(
      await supabase.from('payments').select('*').order('due_date', { ascending: true })
    );
    const byContract = new Map();
    (paymentRows || []).forEach((p) => {
      if (!byContract.has(p.contract_id)) byContract.set(p.contract_id, []);
      byContract.get(p.contract_id).push(p);
    });

    // Events too, grouped by contract, so list/dashboard reflect real signings.
    const eventRows = unwrap(
      await supabase.from('signature_events').select('*').order('server_timestamp', { ascending: true })
    );
    const eventsByContract = new Map();
    (eventRows || []).forEach((e) => {
      if (!e.contract_id) return;
      if (!eventsByContract.has(e.contract_id)) eventsByContract.set(e.contract_id, []);
      eventsByContract.get(e.contract_id).push(e);
    });

    return contractRows.map((row) =>
      contractFromRow(row, byContract.get(row.id) || [], eventsByContract.get(row.id) || [])
    );
  },

  getById: async (id) => {
    const rows = unwrap(
      await supabase.from('contracts').select('*').eq('id', id).limit(1)
    );
    if (!rows || rows.length === 0) return null;
    const paymentRows = unwrap(
      await supabase
        .from('payments')
        .select('*')
        .eq('contract_id', id)
        .order('due_date', { ascending: true })
    );
    // Pull the tamper-evident event ledger so signer details + audit trail show.
    const eventRows = unwrap(
      await supabase
        .from('signature_events')
        .select('*')
        .eq('contract_id', id)
        .order('server_timestamp', { ascending: true })
    );
    return contractFromRow(rows[0], paymentRows || [], eventRows || []);
  },

  // The Certificate of Completion for a signed contract (most recent), with a
  // short-lived signed URL to download the PDF. Returns null if none yet.
  getCertificate: async (contractId) => {
    const rows = unwrap(
      await supabase
        .from('certificates')
        .select('*')
        .eq('contract_id', contractId)
        .order('generated_at', { ascending: false })
        .limit(1)
    );
    if (!rows || rows.length === 0) return null;
    const cert = rows[0];
    // pdf_url is a bucket-prefixed path like "certificates/<contract>/<id>.pdf".
    const path = (cert.pdf_url || '').replace(/^certificates\//, '');
    let downloadUrl = null;
    if (path) {
      const { data } = await supabase.storage.from('certificates').createSignedUrl(path, 300);
      downloadUrl = data?.signedUrl || null;
    }
    return { id: cert.id, sha256: cert.pdf_sha256, generatedAt: cert.generated_at, downloadUrl };
  },

  create: async (data) => {
    // Server-side contract-number generation (avoids client-side race).
    const contractNumber = unwrap(await supabase.rpc('next_contract_number'));

    const row = contractToRow(data);
    row.contract_number = contractNumber;

    const inserted = unwrap(
      await supabase.from('contracts').insert(row).select().single()
    );
    // Fresh contract has no payments yet; auditLog defaults to [] in the mapper.
    return contractFromRow(inserted, []);
  },

  update: async (id, patch) => {
    // contractToRow only emits columns that exist on the table; fields with no
    // column (signer_*, payments, auditLog, consent_*, etc.) are ignored.
    const row = contractToRow(patch);
    if (Object.keys(row).length > 0) {
      unwrap(await supabase.from('contracts').update(row).eq('id', id));
    }
    // Re-fetch fresh row with payments so the return shape matches the old API.
    return contractService.getById(id);
  },

  setAttachment: async (id, attachmentBase64, attachmentName) => {
    // Keep base64 in the text column for now (Storage migration is later).
    unwrap(
      await supabase
        .from('contracts')
        .update({ attachment_url: attachmentBase64, attachment_name: attachmentName })
        .eq('id', id)
    );
    return contractService.getById(id);
  },

  removeAttachment: async (id) => {
    unwrap(
      await supabase
        .from('contracts')
        .update({ attachment_url: null, attachment_name: null })
        .eq('id', id)
    );
    return contractService.getById(id);
  },

  updateStatus: async (id, status, extra) => {
    // Map any extra app fields to their columns (unknown ones are dropped).
    const row = { ...contractToRow(extra || {}), status };
    unwrap(await supabase.from('contracts').update(row).eq('id', id));
    return contractService.getById(id);
  },

  addAuditEntry: async (id, entry) => {
    // Stage 2 NO-OP: the real, tamper-evident audit trail lives in
    // signature_events, which has strict RLS/columns and an append-only trigger.
    // Writing there safely is Stage 4 work. For now we do not write anything and
    // simply return the (re-fetched) contract so the UI does not break.
    // eslint-disable-next-line no-unused-vars
    const _entry = entry;
    // TODO Stage 4: write this audit entry into signature_events (append-only).
    return contractService.getById(id);
  },

  addVersion: async (id, versionEntry) => {
    // Read current version + history, append, increment, write back.
    const rows = unwrap(
      await supabase
        .from('contracts')
        .select('version, version_history')
        .eq('id', id)
        .limit(1)
    );
    if (!rows || rows.length === 0) throw new Error('Contract not found');
    const current = rows[0];
    const history = Array.isArray(current.version_history) ? current.version_history : [];
    const nextVersion = (current.version || 1) + 1;
    unwrap(
      await supabase
        .from('contracts')
        .update({ version_history: [...history, versionEntry], version: nextVersion })
        .eq('id', id)
    );
    return contractService.getById(id);
  },

  delete: async (id) => {
    // Payments cascade on delete (FK on delete cascade).
    unwrap(await supabase.from('contracts').delete().eq('id', id));
  },
};

/* ============================== PAYMENTS ============================== */
export const paymentService = {
  getByContractId: async (contractId) => {
    const rows = unwrap(
      await supabase
        .from('payments')
        .select('*')
        .eq('contract_id', contractId)
        .order('due_date', { ascending: true })
    );
    return (rows || []).map(paymentFromRow);
  },

  getAllOutstanding: async () => {
    // Join to contracts to carry contractTitle/contractNumber/clientId.
    const rows = unwrap(
      await supabase
        .from('payments')
        .select('*, contracts(title, contract_number, client_id)')
        .in('status', ['pending', 'overdue', 'disputed'])
    );
    return (rows || []).map((row) => {
      const c = row.contracts || {};
      const mapped = paymentFromRow(row);
      return {
        ...mapped,
        contractTitle: c.title ?? null,
        contractNumber: c.contract_number ?? null,
        clientId: c.client_id ?? null,
      };
    });
  },

  create: async (contractId, data) => {
    // status defaults to 'pending' unless data overrides it.
    const row = { ...paymentToRow(data), contract_id: contractId };
    if (!('status' in row)) row.status = 'pending';
    const inserted = unwrap(
      await supabase.from('payments').insert(row).select().single()
    );
    return paymentFromRow(inserted);
  },

  replaceAllForContract: async (contractId, paymentDataList) => {
    // Guard: refuse to replace if any existing payment is beyond pending/overdue.
    const existing = unwrap(
      await supabase.from('payments').select('status').eq('contract_id', contractId)
    );
    if (
      (existing || []).some((p) => p.status !== 'pending' && p.status !== 'overdue')
    ) {
      throw new Error('Cannot replace payment milestones once one has been paid or disputed.');
    }
    // Delete all, then insert the new list.
    unwrap(await supabase.from('payments').delete().eq('contract_id', contractId));

    const rows = (paymentDataList || []).map((data) => {
      const row = { ...paymentToRow(data), contract_id: contractId };
      if (!('status' in row)) row.status = 'pending';
      return row;
    });
    if (rows.length === 0) return [];
    const inserted = unwrap(
      await supabase.from('payments').insert(rows).select()
    );
    return (inserted || []).map(paymentFromRow);
  },

  markPaid: async (contractId, paymentId, paidAmount, userId, paidAt) => {
    const updated = unwrap(
      await supabase
        .from('payments')
        .update({
          status: 'paid',
          paid_at: paidAt || new Date().toISOString(),
          paid_amount: paidAmount,
          marked_paid_by: userId,
        })
        .eq('id', paymentId)
        .eq('contract_id', contractId)
        .select()
        .single()
    );
    return paymentFromRow(updated);
  },

  updateStatus: async (contractId, paymentId, status) => {
    const updated = unwrap(
      await supabase
        .from('payments')
        .update({ status })
        .eq('id', paymentId)
        .eq('contract_id', contractId)
        .select()
        .single()
    );
    return paymentFromRow(updated);
  },

  addReminder: async (contractId, paymentId, reminder) => {
    // Read current reminders_sent, append, write back.
    const rows = unwrap(
      await supabase
        .from('payments')
        .select('reminders_sent')
        .eq('id', paymentId)
        .eq('contract_id', contractId)
        .limit(1)
    );
    if (!rows || rows.length === 0) throw new Error('Payment not found');
    const current = Array.isArray(rows[0].reminders_sent) ? rows[0].reminders_sent : [];
    const entry = { id: crypto.randomUUID(), at: new Date().toISOString(), ...reminder };
    const updated = unwrap(
      await supabase
        .from('payments')
        .update({ reminders_sent: [...current, entry] })
        .eq('id', paymentId)
        .eq('contract_id', contractId)
        .select()
        .single()
    );
    return paymentFromRow(updated);
  },
};
